import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"

export default function ObchodnePodmienkyPage() {
  return (
    <div className="container space-y-16">
      <Breadcrumb>
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href="/">Domov</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage>Obchodné podmienky</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>
      <h1 className="mt-4 text-4xl font-bold md:text-5xl">Obchodné podmienky</h1>
      <div className="mb-4 space-y-4 text-sm">
        <p><strong>1. Všeobecné ustanovenia</strong><br />Tieto a reklamné podmienky upravujú práva a zmluvné strany vyplývajúce z uzatvorenej zmluvy uzatvorenej medzi obchodnými partnermi, ktorými je SHARK.SK, j.s.a. zapísaná v Obchodnom registri Okresného súdu Bratislava I, oddiel: Sja, vložka číslo: 28/B, so sídlom Komenského 40, 040 01 Košice &#8211; mestská časť Sever, IČO: 51154439 (ďalej len &#8222;predávajúci&#8220;) a na zákazníkom, ktorej predmetom je kúpa a predaj digitálnych fotografií, fotoproduktov na internetovej stránke elektronického obchodu predávajúceho.</p>
        <p><strong>Kontaktné údaje predajcu:</strong><br />SHARK.SK j.s.a., so sídlom Komenského 40, 040 01 Košice &#8211; mestská časť Sever<br />IČO: 51154439<br />DIČ: 2120614628<br />IČ DPH: SK2120614628</p>
        <p><span style={{ verticalAlign: 'inherit' }}><span style={{ verticalAlign: 'inherit' }}>Prevádzka:&nbsp;</span></span><span style={{ fontSize: '14px', textAlign: 'center' }}>Rozvojová 2, 040 11 Košice</span><br /><span style={{ verticalAlign: 'inherit' }}><span style={{ verticalAlign: 'inherit' }}> Telefón: <span style={{ color: '#ff0000' }}><a style={{ color: '#ff0000' }} href="tel:+421917545003">+421 917 545 003</a></span></span></span><br /><span style={{ verticalAlign: 'inherit' }}><span style={{ verticalAlign: 'inherit' }}>E-mail: </span></span><span style={{ color: '#ff0000' }}><span style={{ verticalAlign: 'inherit' }}><span style={{ verticalAlign: 'inherit' }}>info@printexpert.sk</span></span></span></p>
<p><strong>Dozorný orgán:</strong><br />Slovenská obchodná inšpekcia (SOI)<br />Inšpektorát SOI pre Košický kraj, Vrátna 3, PO BOX A-35, 040 65 Košice 1<br />Odbor dohľadu a právne oddelenie, tel.č. C. 055/729 07 05, 055/622 76 55, fax č. 055/622 46 95<br />http://www.soi.sk<br />http://www.soi.sk/sk/Podavanie-podnetov-staznosti-navrhov-a-ziadosti.soi</p>
<p>1.1 Tieto obchodné a reklamačné podmienky v znení platnom v deň uzatvorenia kúpnej zmluvy sú neoddeliteľnou súčasťou kúpnej zmluvy. V prípade, že predávajúci a kupujúci uzatvoria písomnú kúpnu zmluvu, v ktorej si dohodnú podmienky odchylne od týchto obchodných a reklamačných podmienok, budú ustanovenia kúpnej zmluvy uprednostnené pred týmito obchodnými a reklamačnými podmienkami. Takto dohodnuté podmienky nesmú byť v rozpore s inými právnymi úpravami (skrátenie lehoty na vrátenie tovaru, záručnej doby a pod.)</p>
<p>1.2. Doplnkovou zmluvou sa na účely týchto obchodných a reklamačných podmienok rozumie zmluva, na základe ktorej kupujúci nadobúda tovar alebo je mu poskytnutá služba, ktorá súvisí s predmetom kúpnej zmluvy, ak je tovar dodávaný alebo služba poskytovaná predávajúcim alebo treťou osobou na základe ich dohody.</p>
<p>1.3. Zobrazená kúpna cena za tovar na akejkoľvek internetovej stránke elektronického obchodu, ktorú prevádzkuje predávajúci zahŕňa aj daň z pridanej hodnoty vo výške stanovenej platným právnym predpisom Slovenskej republiky a nezahŕňa cenu za prepravu tovaru alebo iné voliteľné služby. Všetky akcie platia do vypredania zásob, pokiaľ pri konkrétnom tovare nie je uvedené inak.</p>
<p>1.4. Predávajúci si vyhradzuje právo kedykoľvek upraviť cenu tovaru uvedenú na akejkoľvek internetovej stránke elektronického obchodu, ktorú prevádzkuje predávajúci. Zmena ceny tovaru sa nevzťahuje na kúpne zmluvy uzatvorené pred zmenou ceny, bez ohľadu na to, že ešte nedošlo k dodaniu tovaru.</p>
<p>1.5. V prípade, že predávajúci nedodrží svoje povinnosti uvedené v platných právnych predpisoch Slovenskej republiky alebo Európskych spoločenstiev alebo v týchto obchodných a reklamačných podmienkach, môže si kupujúci uplatniť svoje právo voči predávajúcemu prostredníctvom príslušného súdu.</p>
<p><strong>2. Spôsob uzatvárania kúpnej zmluvy </strong></p>
<p>2.1. Návrh na uzavretie kúpnej zmluvy zasiela kupujúci predávajúcemu vo forme vyplneného a odoslaného formulára na internetovej stránke predávajúceho, ktorým zaslal návrh na uzavretie kúpnej zmluvy, predmetom ktorej je odplatný prevod vlastníckeho práva k tovaru označeného kupujúcim za kúpnu cenu a za podmienok, uvedených v tejto objednávke (ďalej len „objednávka“).</p>
<p>2.2. Následne po odoslaní objednávky dostane kupujúci na svoju e-mailovú adresu automaticky vykonávané oznámenie o prijatí objednávky do elektronického systému predávajúceho (ďalej len „potvrdenie doručenia objednávky“). Na e-mailovú adresu kupujúceho môžu byť v prípade potreby zasielané všetky ďalšie informácie ohľadom jeho objednávky.</p>
<p>2.3. Potvrdenie doručenia obsahuje údaje o tom, že predávajúcemu bola doručená objednávka, nie je však akceptovaním návrhu na uzavretie kúpnej zmluvy.</p>
<p>2.4. Potvrdenie objednávky obsahuje informáciu o názve a špecifikácii tovaru, ktorého predaj je predmetom kúpnej zmluvy, ďalej údaje o cene tovaru a/alebo iných služieb, údaj o predpokladanej dodacej lehote tovaru, názov a údaje o mieste, kde má byť tovar dodaný a údaje o prípadnej cene, podmienkach, spôsobe a termíne prepravy tovaru do dohodnutého miesta doručenia tovaru pre kupujúceho, údaje o predávajúcom (obchodné meno, sídlo, IČO, číslo zápisu v obchodnom registri a pod.), prípadne aj iné potrebné údaje.</p>
<p>2.5. Kúpna zmluva je uzavretá doručením akceptácie objednávky v elektronickej alebo písomnej podobe kupujúcemu.</p>
<p>2.6. Predávajúci jasným, jednoznačným, zrozumiteľným a nezameniteľným spôsobom informoval pred odoslaním objednávky kupujúceho o predzmluvných informáciách, týkajúcich sa reklamačných, platobných, obchodných, prepravných a iných podmienok tak, že:</p>
<div>a. o hlavných vlastnostiach tovaru alebo charaktere služby v rozsahu primeranom použitému prostriedku komunikácie a tovaru alebo službe informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho,</div>
<div>b. o obchodnom mene a sídle predávajúceho informoval na príslušnej podstránke elektronického obchodu predávajúceho a v čl. 1 týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>c. o telefónnom čísle predávajúceho a o ďalších údajoch, ktoré sú dôležité pre kontakt kupujúceho s predávajúcim, najmä adresu jeho elektronickej pošty a číslo faxu, ak ich má informoval na príslušnej podstránke elektronického obchodu predávajúceho a v čl. 1 týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>d. o adrese predávajúceho, na ktorej môže kupujúci uplatniť reklamáciu tovaru alebo služby, podať sťažnosť alebo iný podnet informoval v čl. 1 týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>e. o celkovej cene tovaru alebo služby vrátane dane z pridanej hodnoty a všetkých ostatných daní alebo ak vzhľadom na povahu tovaru alebo služby nemožno cenu primerane určiť vopred, spôsob, akým sa vypočíta, ako aj o nákladoch na dopravu, dodanie, poštovné a iné náklady a poplatky, alebo, ak tieto náklady a poplatky nemožno určiť vopred o skutočnosti, že kupujúci ich bude povinný uhradiť informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho,</div>
<div>f. o platobných podmienkach, dodacích podmienkach, o lehote, do ktorej sa predávajúci zaväzuje dodať tovar alebo poskytnúť službu, o informácii o postupoch uplatňovania a vybavovania reklamácií, sťažností a podnetov kupujúceho informoval v príslušných článkoch týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>g. o informácii o práve kupujúceho odstúpiť od kúpnej zmluvy, o podmienkach, lehote a postupe pri uplatňovaní práva na odstúpenie od zmluvy informoval v čl. 10 týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>h. o poskytnutí formuláru na odstúpenie od kúpnej zmluvy informoval v čl. 10 a v prílohe týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho; predávajúci zároveň poskytol samotný formulár na odstúpenie od kúpnej zmluvy v prílohe týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho</div>
<div>i. o informácii, že ak kupujúci odstúpi od kúpnej zmluvy, bude znášať náklady spojené s vrátením tovaru predávajúcemu podľa § 10 ods. 3 zákona č. 102/2014 Z.z. o ochrane spotrebiteľa pri predaji tovaru alebo poskytovaní služieb na základe zmluvy uzavretej na diaľku alebo zmluvy uzavretej mimo prevádzkových priestorov predávajúceho a o zmene a doplnení niektorých zákonov (ďalej len \\\&#8220;Zákon o ochrane spotrebiteľa pri predaji na diaľku\\\&#8220;., a ak odstúpi od kúpnej zmluvy aj náklady na vrátenie tovaru, ktorý vzhľadom na jeho povahu nie je možné vrátiť prostredníctvom pošty informoval v čl. 10 týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>j. o povinnosti kupujúceho uhradiť predávajúcemu cenu za skutočne poskytnuté plnenie podľa § 10 ods. 5 Zákona o ochrane spotrebiteľa pri predaji na diaľku, ak kupujúci odstúpi od zmluvy o službách po tom, čo udelil predávajúcemu výslovný súhlas podľa § 4 ods. 6 Zákona o ochrane spotrebiteľa pri predaji na diaľku informoval v čl. 10 týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>k. o okolnostiach, za ktorých kupujúci stráca právo na odstúpenie od zmluvy informoval v čl. 10 týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>l. o poučení o zodpovednosti predávajúceho za vady tovaru alebo služby podľa ust. § 622 a 623 Občianskeho zákonníka informoval v čl. 8 týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>m. o existencii a podrobnostiach záruky poskytovanej výrobcom alebo predávajúcim podľa prísnejších zásad ako ustanovuje ust. § 502 Občianskeho zákonníka, ak ju výrobca alebo predávajúci poskytuje, ako aj informáciu o existencii a podmienkach pomoci a službách poskytovaných kupujúcemu po predaji tovaru alebo poskytnutí služby, ak sa taká pomoc poskytuje informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho a čl. 9 týchto obchodných a reklamačných podmienok, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>n. o existencii príslušných kódexov správania, ktoré sa predávajúci zaviazal dodržiavať, a o spôsobe, akým sa môže kupujúci s nimi oboznámiť alebo získať ich znenie informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho,</div>
<div>o. o dĺžke trvania zmluvy, ak ide o zmluvu uzavretú na dobu určitú; ak ide o zmluvu uzavretú na dobu neurčitú alebo ak ide o zmluvu, pri ktorej sa automaticky predlžuje jej platnosť, aj informáciu o podmienkach vypovedania zmluvy informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho a v týchto obchodných a reklamačných podmienkach, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>p. o minimálnej dĺžke trvania záväzkov kupujúceho vyplývajúcich z kúpnej zmluvy, ak z kúpnej zmluvy vyplýva pre kupujúceho takýto záväzok informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho a v týchto obchodných a reklamačných podmienkach, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho, q. o povinnosti kupujúceho zaplatiť preddavok alebo poskytnúť inú finančnú zábezpeku na žiadosť predávajúceho a o podmienkach, ktoré sa na jeho poskytnutie vzťahujú, ak z kúpnej zmluvy vyplýva pre kupujúceho takýto záväzok informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho a v týchto obchodných a reklamačných podmienkach, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>r. o funkčnosti vrátane použiteľných technických ochranných opatrení na zabezpečenie elektronického obsahu, ak je to vhodné informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho a v týchto obchodných a reklamačných podmienkach, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>s. o kompatibilite elektronického obsahu s hardvérom a softvérom, o ktorých predávajúci vie alebo je rozumné očakávať, že o nich vie, ak je to vhodné informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho a v týchto obchodných a reklamačných podmienkach, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>t. o možnosti a podmienkach riešenia sporu mimosúdnou cestou prostredníctvom systému alternatívneho riešenia sporov, ak sa predávajúci zaviazal tento systém využívať informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho a v týchto obchodných a reklamačných podmienkach, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>u. o úkonoch potrebných na uzatvorenie kúpnej zmluvy tak, že tieto potrebné úkony popísal v týchto obchodných a reklamačných podmienkach, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>v. o tom, že kúpna zmluva bude uložená v elektronickej podobe u predajcu a je kupujúcemu dostupná po tom, ako si ju kupujúci písomne vyžiada informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho a v týchto obchodných a reklamačných podmienkach, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho,</div>
<div>
<p>w) o tom, že jazykom ponúkaným na uzatvorenie zmluvy je slovenský jazyk informoval na príslušnej katalógovej stránke elektronického obchodu predávajúceho a v týchto obchodných a reklamačných podmienkach, ktoré sú umiestnené na príslušnej podstránke elektronického obchodu predávajúceho.</p>
<p>2.7. Ak predávajúci nesplnil informačnú povinnosť o úhrade dodatočných poplatkov alebo iných nákladov podľa bodu 2.6. písm. e. týchto obchodných a reklamačných podmienok alebo o nákladoch na vrátenie tovaru podľa bodu 2.6. písm. i. týchto obchodných a reklamačných podmienok, kupujúci nie je povinný tieto dodatočné náklady alebo poplatky uhradiť.</p>
<p><strong>3. Práva a povinnosti predávajúceho</strong></p>
<p>3.1. Predávajúci je povinný:</p>
</div>
<div>a. dodať na základe objednávky potvrdenej akceptáciou kupujúcemu tovar v dohodnutom množstve, kvalite a lehote a zabaliť ho alebo vybaviť na prepravu spôsobom potrebným na jeho uchovanie a ochranu,</div>
<div>b. zabezpečiť, aby dodaný tovar spĺňal platné právne predpisy SR,</div>
<div>c. bezodkladne po uzavretí kúpnej zmluvy, najneskôr však spolu s dodaním tovaru poskytnúť kupujúcemu potvrdenie o uzavretí kúpnej zmluvy na trvanlivom nosiči, napríklad prostredníctvom e- mailu. Potvrdenie musí obsahovať všetky informácie uvedené v bode 2.6. vrátane formulára na odstúpenie od kúpnej zmluvy.</div>
<div>
<p>d. odovzdať kupujúcemu najneskôr spolu s tovarom v písomnej alebo elektronickej podobe všetky doklady potrebné na prevzatie a užívanie tovaru a ďalšie doklady predpísané platnými právnymi predpismi SR (návody v slovenskom jazyku, záručný list, dodací list, daňový doklad).</p>
<p>3.2. Predávajúci má právo na riadne a včasné zaplatenie kúpnej ceny od kupujúceho za dodaný tovar.</p>
<p>3.3. Predávajúci si vyhradzuje právo dstúpiť od kúpnej zmluvy (stornovať objednávku alebo jej časť) v prípade, ak sa tovar už nevyrába alebo nedodáva alebo sa výrazným spôsobom zmenila cena dodávateľa tovaru a nedohodne sa s kupujúcim na náhradnom plnení.</p>
</div>
<p>3.4. V prípade, že táto situácia nastane, predávajúci bude okamžite kontaktovať kupujúceho za účelom dohody o ďalšom postupe. V prípade, že kupujúci zaplatil už časť alebo celú sumu kúpnej ceny, bude kupujúcemu príslušná čiastka prevedená na ním určený účet v lehote 14-tich kalendárnych dní.</p>
<p><strong>4. Práva a povinnosti kupujúceho</strong></p>
<p>4.1. Kupujúci bol predávajúcim oboznámený s tým, že súčasťou objednávky je povinnosť zaplatiť cenu.</p>
<p>4.2. Kupujúci je povinný:</p>
<div>a. prevziať objednaný a dodaný tovar,</div>
<div>
<p>b. zaplatiť predávajúcemu dohodnutú kúpnu cenu v dohodnutej lehote splatnosti vrátane nákladov na doručenie tovaru.</p>
<p>4.3. Kupujúci má právo na dodanie tovaru v množstve, kvalite, termíne a mieste dohodnutom zmluvnými stranami.</p>
<p><strong>5. Dodacie a platobné podmienky</strong></p>
<p>5.1. Obvyklá dostupnosť tovaru s termínom jeho expedície je uvedená pri každom tovare na internetovej stránke elektronického obchodu.</p>
<p>5.2. Ak sa predávajúci a kupujúci v kúpnej zmluve nedohodli inak, predávajúci je povinný dodať vec kupujúcemu bezodkladne, najneskôr do 30 dní odo dňa uzavretia kúpnej zmluvy. Ak predávajúci nesplnil svoj záväzok dodať vec v lehote podľa prvej vety, kupujúci ho vyzve, aby dodal vec v ním poskytnutej dodatočnej primeranej lehote. Ak predávajúci nedodá vec ani v tejto dodatočnej primeranej lehote, kupujúci je oprávnený odstúpiť od zmluvy.</p>
<p>5.3. Predávajúci je oprávnený vyzvať kupujúceho na prevzatie tovaru aj pred uplynutím lehoty na dodanie tovaru dohodnutej v kúpnej zmluve.</p>
<p>5.4. Zobrazenie tovaru na akejkoľvek internetovej stránke elektronického obchodu, ktorú prevádzkuje predávajúci je len ilustračné. Hmotnosť, rozmery a ostatné údaje o tovare obsiahnuté v katalógoch, prospektoch a iných písomnostiach predávajúceho umiestnenými na internetovej stránke elektronického obchodu predávajúceho sú udávané výrobcom a môžu sa odlišovať od skutočnosti o ± 1% z uvedenej hodnoty.</p>
<p>5.5. Kupujúci je povinný prevziať tovar v mieste, ktoré je predávajúcim alebo jeho zástupcom, povereným doručiť tovar a kupujúcim dohodnuté v kúpnej zmluve alebo iným spôsobom v čase pred doručovaním tovaru (ďalej len „Miesto“). Kupujúci je povinný prevziať tovar v časovom rozsahu, ktoré je predávajúcim alebo jeho zástupcom, povereným doručiť tovar a kupujúcim dohodnuté v kúpnej zmluve alebo iným spôsobom v čase pred doručovaním tovaru (ďalej len „Časový rozsah“).</p>
<p>5.6. V prípade, ak predávajúci dopraví tovar kupujúcemu na Miesto a v Časovom rozsahu, kupujúci je povinný prevziať tovar osobne alebo zabezpečiť, aby tovar prevzala osoba, ktorú splnomocní pre prípad svojej neprítomnosti na prevzatie tovaru a podpísať protokol o zaplatení kúpnej ceny a doručení a odovzdaní tovaru. Tretia osoba splnomocnená na prevzatie tovaru je povinná predložiť predávajúcemu kópiu akceptácie objednávky. Tovar sa považuje za dodaný a prevzatý okamihom doručenia tovaru kupujúcemu. Doručením tovaru kupujúcemu sa rozumie dodanie tovaru na Miesto, jeho prevzatie kupujúcim alebo treťou osobou splnomocnenou kupujúcim a podpísanie protokolu o zaplatení kúpnej ceny a doručení a odovzdaní tovaru kupujúcim alebo treťou osobou splnomocnenou kupujúcim.</p>
<p>5.7. Ak bude potrebné dodanie tovaru opakovať z dôvodu neprítomnosti kupujúceho na Mieste a v Časovom rozsahu alebo v prípade, ak kupujúci bez predchádzajúceho písomného odstúpenia od kúpnej zmluvy neprevezme tovar do 7 dní po márnom uplynutí Časového rozsahu, vzniká predávajúcemu nárok na uplatnenie náhrady za vzniknutú škodu vo výške skutočných nákladov na pokus o neúspešné doručenie tovaru na Miesto.</p>
<p>5.8. Kupujúci je povinný skontrolovať zásielku, teda tovar ako aj jeho obal ihneď po doručení v prítomnosti zástupcu predávajúceho. V prípade zistenia existencie vady tovaru je zástupca predávajúceho povinný umožniť kupujúcemu vyhotoviť záznam o rozsahu a povahe vady tovaru, ktorého správnosť potvrdí zástupca predávajúceho. Na základe takto vyhotoveného záznamu doručeného predávajúcemu môže následne kupujúci odmietnuť prevziať dodaný tovar s vadou alebo potvrdiť doručenie tovaru s vadou a následne v zmysle čl. 8 týchto obchodných a reklamačných podmienok uplatniť reklamáciu vád tovaru u predávajúceho alebo určenej osoby. V prípade, ak kupujúci odmietne prevziať dodaný tovar s vadou, všetky účelne vynaložené náklady na vrátenie tovaru predávajúcemu znáša predávajúci. 5.9. Kupujúci je oprávnený v prípade nedodania tovaru predávajúcim v lehote uvedenej v bode 5.2. týchto obchodných podmienok odstúpiť od kúpnej zmluvy a predávajúci je povinný vrátiť kupujúcemu už zaplatenú časť kúpnej ceny v lehote 14 dní od doručenia odstúpenia od kúpnej zmluvy bezhotovostným prevodom na bankový účet kupujúceho určený kupujúcim.</p>
<p><strong>6. Kúpna cena</strong></p>
<p>6.1. Kúpna cena za tovar dohodnutá v kúpnej zmluve medzi predávajúcim a kupujúcim je uvedená v akceptácii objednávky (ďalej len &#8222;kúpna cena&#8220;). Ak je kúpna cena uvedená v potvrdení doručenia objednávky vyššia ako cena za identický tovar uvedená v ponuke elektronického obchodu v čase odoslania objednávky kupujúcim, predávajúci doručí kupujúcemu elektronickú správu s informáciou o ponuke novej kúpnej ceny v inej výške, ktorá sa považuje za návrh predávajúceho na uzavretie novej kúpnej zmluvy, ktorý musí kupujúci výslovne potvrdiť e-mailom alebo písomne, aby došlo k platnému uzatvoreniu kúpnej zmluvy.</p>
<p>6.2. Kupujúci je povinný zaplatiť predávajúcemu kúpnu cenu vrátane nákladov na doručenie tovaru v hotovosti, resp. platobnou kartou pri osobnom prevzatí tovaru, dobierkou v mieste dodania tovaru alebo bezhotovostným prevodom na účet predávajúceho, uvedený v akceptácii objednávky alebo na internetovej stránke predávajúceho v čase pred prevzatím tovaru. Kupujúci môže využiť aj možnosť spotrebiteľského splátkového úveru – viac informácií získate v sekcii O nákupe &#8211; predaj na splátky.</p>
<p>6.3. V prípade, ak kupujúci zaplatí predávajúcemu kúpnu cenu bezhotovostným prevodom, za deň platby sa považuje deň, kedy bola celá kúpna cena pripísaná na účet predávajúceho.</p>
<p>6.4. Kupujúci je povinný zaplatiť predávajúcemu kúpnu cenu za dohodnutý tovar v lehote podľa kúpnej zmluvy, najneskôr však pri prevzatí tovaru.</p>
<p>6.5. V prípade, ak kupujúci nezaplatí predávajúcemu celú kúpnu cenu do momentu dodania tovaru na Miesto a zmluvné strany sa nedohodli na zaplatení kúpnej ceny za tovar v splátkach, predávajúci je oprávnený odoprieť dodanie tovaru kupujúcemu.</p>
<p>6.6. Náklady spojené s montážou a vynáškou tovaru nie sú zahrnuté v kúpnej cene a predávajúci tieto služby nie je povinný kupujúcemu poskytnúť.</p>
<p><strong>7. Nadobudnutie vlastníctva a prechod nebezpečenstva škody na tovare</strong></p>
<p>7.1. Kupujúci nadobúda vlastnícke právo k tovaru až úplným zaplatením celej kúpnej ceny za tovar.</p>
<p>7.2. Nebezpečenstvo škody na tovare prechádza na kupujúceho v čase, keď kupujúci alebo tretia osoba splnomocnená kupujúcim prevezme tovar od predávajúceho alebo od jeho zástupcu, povereného doručiť tovar, alebo keď tak neurobí včas, tak v čase, keď predávajúci umožní kupujúcemu nakladať s tovarom a kupujúci tovar neprevezme.</p>
<p><strong>8. Reklamačný poriadok (zodpovednosť za vady, záruka, reklamácie)</strong></p>
<p>8.1. Ak ide o vadu tovaru, ktorú možno odstrániť, má kupujúci právo, aby bola bezplatne, včas a riadne odstránená. Predávajúci je povinný vadu bez zbytočného odkladu odstrániť.</p>
<p>8.2. Kupujúci môže namiesto odstránenia vady požadovať výmenu tovaru, alebo ak sa vada týka len súčasti tovaru, výmenu súčasti, ak tým predávajúcemu nevzniknú neprimerané náklady vzhľadom na cenu tovaru alebo závažnosť vady.</p>
<p>8.3. Predávajúci môže vždy namiesto odstránenia vady vymeniť vadný tovar za bezvadný, ak to kupujúcemu nespôsobí závažné ťažkosti.</p>
<p>8.4. Ak ide o vadu tovaru, ktorú nemožno odstrániť a ktorá bráni tomu, aby sa tovaru mohol riadne užívať ako vec bez vady, má kupujúci právo na výmenu tovaru alebo má právo od kúpnej zmluvy odstúpiť. Tie isté práva prislúchajú kupujúcemu, ak ide síce o odstrániteľné vady, ak však kupujúci nemôže pre opätovné vyskytnutie sa vady po oprave alebo pre väčší počet vád tovar riadne užívať.</p>
<p>8.5. Ak ide o iné neodstrániteľné vady, má kupujúci právo na primeranú zľavu z ceny tovaru.</p>
<p>8.6. Predávajúci poučil kupujúceho o jeho právach, ktoré mu vyplývajú z ust. § 622 Občianskeho zákonníka (bod 8.1. až 8.3. týchto obchodných a reklamačných podmienok) a právach, ktoré mu vyplývajú z ust. § 623 Občianskeho zákonníka (bod 8.4. až 8.5. týchto obchodných a reklamačných podmienok) tak, že umiestnil tieto obchodné a reklamačné podmienky na príslušnej podstránke elektronického obchodu predávajúceho a kupujúci mal možnosť si ich prečítať v čase pred odoslaním objednávky.</p>
<p>8.7. Predávajúci zodpovedá za vady tovaru v zmysle platných predpisov SR a kupujúci je povinný reklamáciu uplatniť u predávajúceho alebo u určenej osoby. Informácie o určených osobách a servisných miestach pre záručný a pozáručný servis sú uvedené na zadnej strane záručného listu alebo ich poskytne predávajúci kupujúcemu na požiadanie telefonicky alebo prostredníctvom e-mailu.</p>
<p>8.8. Na vybavovanie reklamácií sa vzťahuje platný reklamačný poriadok predávajúceho, teda čl. 8 týchto obchodných a reklamačných podmienok. Kupujúci bol riadne oboznámený s reklamačným poriadkom a informovaný o podmienkach a spôsobe reklamácie tovaru vrátane údajov o tom, kde možno reklamáciu uplatniť, a o vykonávaní záručných opráv v súlade s ust. § 18 ods. 1 zákona č. 250/2007 Z . z. o ochrane spotrebiteľa a o zmene zákona Slovenskej národnej rady č. 372/1990 Zb. o priestupkoch v znení neskorších predpisov (ďalej len \\\&#8220;Zákon\\\&#8220;) v čase pred uzavretím kúpnej zmluvy tak, že umiestnil tieto obchodné a reklamačné podmienky na príslušnej podstránke elektronického obchodu predávajúceho a kupujúci mal možnosť si v čase pred odoslaním objednávky prečítať ich.</p>
<p>8.9. Reklamačný poriadok sa vzťahuje na tovar zakúpený kupujúcim od predávajúceho vo forme elektronického obchodu na internetovej stránke elektronického obchodu predávajúceho.</p>
<p>8.10. Kupujúci má právo uplatniť si u predávajúceho zodpovednosť za vadu tovaru týkajúcu sa len tovaru, ktorý vykazuje vady, za ktoré zodpovedá výrobca, dodávateľ alebo predávajúci, vzťahuje sa naň záruka a bol zakúpený u predávajúceho.</p>
<p>8.11. Ak tovar vykazuje vady, kupujúci má právo uplatniť reklamáciu v prevádzkarni predávajúceho v súlade s ust. § 18 ods. 2 Zákona tak, že doručí tovar do prevádzkarne predávajúceho a doručí predávajúcemu prejav vôle kupujúceho uplatniť si svoje právo podľa bodov 8.1. až 8.5. týchto obchodných a reklamačných podmienok (ďalej len „Oznámenie o uplatnení reklamácie“) napr. vo forme vyplneného formulára na uplatnenie reklamácie, ktorý je umiestnený na príslušnej podstránke elektronického obchodu predávajúceho. Predávajúci odporúča tovar pri jeho zasielaní na reklamáciu poistiť. Zásielky na dobierku predávajúci nepreberá. Kupujúci je povinný v Oznámení o uplatnení reklamácie pravdivo uviesť všetky požadované informácie, najmä presne označiť druh a rozsah vady tovaru; kupujúci zároveň uvedie, ktoré zo svojich práv vyplývajúcich z ust. § 622 a 633 Občianskeho zákonníka uplatňuje. Kupujúci má právo uplatniť reklamáciu aj u osoby oprávnenej výrobcom tovaru na vykonávanie záručných opráv (ďalej len „určená osoba“). Zoznam určených osôb je uvedený v záručnom liste alebo ho kupujúcemu zašle na jeho žiadosť predávajúci.</p>
<p>8.12. Reklamačné konanie týkajúce sa tovaru, ktorý sa dá doručiť predávajúcemu začína dňom, kedy sú splnené kumulatívne všetky nasledujúce podmienky:</p>
</div>
<div>a. doručenie Oznámenia o uplatnení reklamácie predávajúcemu,</div>
<div>b. doručenie reklamovaného tovaru od kupujúceho predávajúcemu alebo určenej osobe,</div>
<div>
<p>c. doručenie prístupových kódov, hesiel a pod. k reklamovanému tovaru predávajúcemu, ak sú tieto údaje nevyhnutné na riadne vybavenie reklamácie;</p>
<p>8.13. Ak je predmetom reklamácie tovar, ktorý sa nedá objektívne doručiť predávajúcemu alebo ktorý je pevne zabudovaný, kupujúci je okrem splnenia podmienok podľa bodov 8.12 písm. a) a c) týchto reklamačných a obchodných podmienok povinný poskytnúť všetku potrebnú súčinnosť na vykonanie obhliadky reklamovaného tovaru predávajúcim alebo treťou osobou určenou predávajúcim. Reklamačné konanie týkajúce sa tovaru, ktorý sa nedá objektívne doručiť predávajúcemu alebo ktorý je pevne zabudovaný začína dňom, kedy bola vykonaná obhliadka tovaru podľa prvej vety. Ak však predávajúci alebo ním určená tretia osoba napriek poskytnutej potrebnej súčinnosti zo strany kupujúceho nezabezpečí vykonanie obhliadky v primeranej lehote, najneskôr však do 10 dní od doručenia Oznámenia o uplatnení reklamácie predávajúcemu, reklamačné konanie začína dňom doručenia Oznámenia o uplatnení reklamácie predávajúcemu.</p>
<p>8.14. Predávajúci alebo určená osoba vydá kupujúcemu potvrdenie o uplatnení reklamácie tovaru vo vhodnej forme zvolenej predávajúcim, napr. vo forme mailu alebo v písomnej podobe, v ktorom je povinný presne označiť reklamované vady tovaru a ešte raz poučí spotrebiteľa o jeho právach, ktoré mu vyplývajú z bodu 8.1. až 8.3. týchto obchodných a reklamačných podmienok (ust. § 622 Občianskeho zákonníka) a právach, ktoré mu vyplývajú z bodu 8.4. až 8.5. týchto obchodných a reklamačných podmienok (ust. § 623 Občianskeho zákonníka). Ak je reklamácia uplatnená prostredníctvom prostriedkov diaľkovej komunikácie, predávajúci je povinný potvrdenie o uplatnení reklamácie doručiť kupujúcemu ihneď; ak nie je možné potvrdenie doručiť ihneď, musí sa doručiť bez zbytočného odkladu, najneskôr však spolu s dokladom o vybavení reklamácie; potvrdenie o uplatnení reklamácie sa nemusí doručovať, ak kupujúci má možnosť preukázať uplatnenie reklamácie iným spôsobom.</p>
<p>8.15. Kupujúci je oprávnený rozhodnúť sa, ktoré zo svojich práv v zmysle ust. § 622 a ust. § 623 Občianskeho zákonníka uplatňuje a zároveň je povinný bezodkladne informáciu o svojom rozhodnutí doručiť predávajúcemu. Na základe rozhodnutia kupujúceho, ktoré zo svojich práv v zmysle ust. § 622 a ust. § 623 Občianskeho zákonníka uplatňuje je predávajúci alebo určená osoba povinná určiť spôsob vybavenia reklamácie podľa ust. § 2 písm. m) Zákona ihneď, v zložitejších prípadoch do 3 dní od začiatku reklamačného konania, v odôvodnených prípadoch, najmä ak sa vyžaduje zložité technické zhodnotenie stavu tovaru najneskôr do 30 dní odo dňa začiatku reklamačného konania. Po určení spôsobu vybavenia reklamácie predávajúci alebo určená osoba reklamáciu vybaví ihneď, v odôvodnených prípadoch možno reklamáciu vybaviť aj neskôr. Vybavenie reklamácie však nesmie trvať dlhšie ako 30 dní odo dňa uplatnenia reklamácie. Po márnom uplynutí lehoty na vybavenie reklamácie má spotrebiteľ právo od zmluvy odstúpiť alebo má právo na výmenu tovaru za nový tovar.</p>
<p>8.16. Ak kupujúci reklamáciu tovaru uplatnil počas prvých 12 mesiacov od uzavretia kúpnej zmluvy, môže predávajúci vybaviť reklamáciu zamietnutím len na základe vyjadrenia znalca alebo stanoviska vydaného autorizovanou, notifikovanou alebo akreditovanou osobou alebo stanoviska určenej osoby (ďalej len “odborné posúdenie tovaru“). Bez ohľadu na výsledok odborného posúdenia nemôže predávajúci od kupujúceho vyžadovať úhradu nákladov na odborné posúdenie tovaru ani iné náklady súvisiace s odborným posúdením tovaru.</p>
<p>8.17. Ak kupujúci reklamáciu výrobku uplatnil po 12 mesiacoch od uzavretia kúpnej zmluvy a predávajúci ju zamietol, osoba, ktorá reklamáciu vybavila, je povinná v doklade o vybavení reklamácie uviesť, komu môže kupujúci zaslať tovar na odborné posúdenie. Ak kupujúci tovar zašle na odborné posúdenie určenej osobe uvedenej v doklade o vybavení reklamácie, náklady odborného posúdenia tovaru, ako aj všetky ostatné s tým súvisiace účelne vynaložené náklady znáša predávajúci bez ohľadu na výsledok odborného posúdenia. Ak kupujúci odborným posúdením preukáže zodpovednosť predávajúceho za reklamovanú vadu tovaru, môže reklamáciu uplatniť znova; počas vykonávania odborného posúdenia tovaru záručná doba neplynie. Predávajúci je povinný kupujúcemu uhradiť do 14 dní odo dňa znova uplatnenej reklamácie všetky náklady vynaložené na odborné posúdenie tovaru, ako aj všetky s tým súvisiace účelne vynaložené náklady. Znova uplatnenú reklamáciu nemožno zamietnuť.</p>
<p>8.18. Kupujúci nemá právo uplatniť si právo zodpovednosti za vady, o ktorých bol predávajúcim v dobe uzatvárania zmluvy upozornený, alebo o ktorých s prihliadnutím k okolnostiam, za ktorých bola kúpna zmluva uzatvorená, musel vedieť.</p>
<p>8.19. Predávajúci si vyhradzuje právo nahradiť vadný tovar za iný bezvadný tovar s rovnakými alebo lepšími technickými parametrami, ak to kupujúcemu nespôsobí závažné ťažkosti.</p>
<p>8.20. Predávajúci nezodpovedá za vady tovaru:</p>
</div>
<div>a. ak ide o zjavnú vadu, ktorú kupujúci mohol zistiť kontrolou zásielky pri doručení tovaru a ktorú neoznámil zástupcovi predávajúcemu v súlade s bodom 5.8. týchto reklamačných a obchodných podmienok,</div>
<div>b. ak kupujúci neuplatnil svoje právo, týkajúce sa zodpovednosti predávajúceho za vadu tovaru do konca záručnej doby tovaru,</div>
<div>c. ak je vadou tovaru mechanické poškodenie tovaru spôsobené kupujúcim,</div>
<div>d. ak vada tovaru vznikla používaním tovaru v podmienkach, ktoré nezodpovedajú svojou intenzitou, vlhkosťou, chemickými a mechanickými vplyvmi prirodzenému prostrediu tovaru,</div>
<div>e. ak vada tovaru vznikla neodborným zaobchádzaním, obsluhou, alebo zanedbaním starostlivosti o tovar,</div>
<div>f. ak vada tovaru vznikla poškodením tovaru nadmerným zaťažovaním, alebo používaním v rozpore s podmienkami uvedenými v dokumentácii alebo všeobecnými zásadami obvyklého používania tovaru,</div>
<div>g. ak vada tovaru vznikla poškodením tovaru neodvrátiteľnými a/alebo nepredvídateľnými udalosťami,</div>
<div>h. ak vada tovaru vznikla poškodením tovaru náhodnou skazou a náhodným zhoršením,</div>
<div>i. ak vada tovaru vznikla neodborným zásahom, poškodením vodou, ohňom, statickou či atmosférickou elektrinou alebo iným zásahom vyššej moci,</div>
<div>
<p>j. ak vada tovaru vznikla zásahom do tovaru k tomu neoprávnenej osoby.</p>
<p>8.21. Predávajúci je povinný vybaviť reklamáciu a ukončiť reklamačné konanie jedným z nasledujúcich spôsobov:</p>
</div>
<div>a. odovzdaním opraveného tovaru,</div>
<div>b. výmenou tovaru,</div>
<div>c. vrátením kúpnej ceny tovaru,</div>
<div>d. vyplatením primeranej zľavy z ceny tovaru,</div>
<div>e. písomnou výzvou na prevzatie predávajúcim určeného plnenia,</div>
<div>
<p>f. odôvodneným zamietnutím reklamácie tovaru.</p>
<p>8.22. Predávajúci je povinný o spôsobe určenia vybavenia reklamácie a o vybavení reklamácie kupujúcemu vydať písomný doklad najneskôr do 30 dní odo dňa uplatnenia reklamácie osobne, prostredníctvom poskytovateľa poštovej alebo kuriérskej alebo donáškovej služby. O výsledku vybavenia reklamácie bude predávajúci informovať kupujúceho bezprostredne po ukončení reklamačného konania telefonicky alebo e-mailom a zároveň mu bude spolu s tovarom, resp. prostredníctvom e-mailu doručený doklad o vybavení reklamácie.</p>
<p>8.23. Záručná doba je 24 mesiacov odo dňa doručenia tovaru, pokiaľ nie je pre konkrétne prípady stanovená záručná doba iná. Zasielané produkty športovej výživy, potraviny v darčekových košoch a krmivá pre zvieratá majú dobu minimálnej trvanlivosti viac ako 2 mesiace pred dátumom spotreby, v prípade kratšej exspiračnej doby kontaktuje predávajúci kupujúceho telefonicky, alebo e-mailom a zásielka je odoslaná iba so súhlasom kupujúceho.</p>
<p>8.24. Záručná doba sa predlžuje o dobu, po ktorú kupujúci nemohol používať tovar z dôvodu záručnej opravy tovaru.</p>
<p>8.25. V prípade výmeny tovaru za nový dostane kupujúci doklad, na ktorom bude uvedená informácia o výmene tovaru, a prípadné ďalšie reklamácie sa uplatňujú na základe kúpnej zmluvy a tohto reklamačného dokladu. V prípade výmeny tovaru za nový začne plynúť záručná doba znovu od prevzatia nového tovaru, ale iba na nový tovar.</p>
<p>8.26. Pokiaľ ide o odstrániteľnú vadu, bude reklamácia vybavená v závislosti od rozhodnutia kupujúceho podľa bodu 8.15. týchto reklamačných a obchodných podmienok nasledujúcim spôsobom:</p>
</div>
<div>a. predávajúci zabezpečí odstránenie vady, alebo</div>
<div>
<p>b. predávajúci vadný tovar vymení.</p>
<p>8.27. Pokiaľ ide o odstrániteľnú vadu a kupujúci neurčí bezodkladne podľa bodu 8.15. týchto reklamačných a obchodných podmienok, aký spôsobom má byť reklamácia vybavená, predávajúci reklamáciu vybaví odstránením vady.</p>
<p>8.28. Pokiaľ sa jedná vadu, ktorú nemožno odstrániť, alebo o jednu viac krát opakovanú odstrániteľnú vadu, alebo o väčší počet rôznych odstrániteľných vád, ktoré bránia tomu, aby mohol byť tovar riadne užívaný ako bez vady, predávajúci vybaví v závislosti od rozhodnutia kupujúceho podľa bodu 8.15. týchto reklamačných a obchodných podmienok reklamáciu nasledujúcim spôsobom:</p>
</div>
<div>a. výmenou tovaru za iný funkčný tovar rovnakých alebo lepších technických parametrov, alebo</div>
<div>
<p>b. v prípade, že nemôže predávajúci vykonať výmenu tovaru za iný, vybaví reklamáciu vrátením kúpnej ceny za tovar.</p>
<p>8.29. Pokiaľ sa jedná vadu, ktorú nemožno odstrániť, alebo o jednu viac krát opakovanú odstrániteľnú vadu, alebo o väčší počet rôznych odstrániteľných vád, ktoré bránia tomu, aby mohol byť tovar riadne užívaný ako bez vady a kupujúci bezodkladne neurčí podľa bodu 8.15. týchto reklamačných a obchodných podmienok, aký spôsobom má byť reklamácia vybavená, predávajúci reklamáciu vybaví výmenou tovaru za iný funkčný tovar rovnakých alebo lepších technických parametrov.</p>
<p>8.30. Vybavenie reklamácie sa vzťahuje len na vady uvedené v Oznámení o uplatnení reklamácie a v potvrdení o uplatnení reklamácie tovaru podľa bodu 8.14. týchto reklamačných a obchodných podmienok.</p>
<p>8.31. Pre účely reklamácie sa za opätovné vyskytnutie sa odstrániteľnej vady po oprave považuje situácia, keď sa po prvej oprave veci rovnaká vada vyskytne ešte najmenej dvakrát.</p>
<p>8.32. Pre účely reklamácie za za väčší počet odstrániteľných vád považuje situácia, keď sa na veci súčasne vyskytnú aspoň tri rôzne odstrániteľné vady.</p>
<p>8.33. Oprávnenie kupujúceho na uplatnenie reklamácie vady tovaru je po tom, ako využil svoje právo a požiadal predávajúceho o odstránenie vady tovaru podľa bodu 8.1. týchto reklamačných a obchodných podmienok skonzumované a bez ohľadu na výsledok reklamácie už opätovne nie je oprávnený pre tú istú jedinečnú vadu (nie vadu rovnakého druhu) uplatňovať reklamáciu opakovane.</p>
<p>8.34. Ustanovenia čl. 8 týchto reklamačných a obchodných podmienok výslovne neplatia pre subjekty nespĺňajúce definíciu spotrebiteľa uvedenú v ust. § 2 písm. a) Zákona.</p>
</div>
<p>8.35. V prípade, že kupujúci (spotrebiteľ) nebol spokojný s vybavením reklamácie predávajúcim alebo keď sa kupujúci (spotrebiteľ) obrátil na predávajúceho so žiadosťou o nápravu a nebol spokojný so spôsobom, ktorým predávajúci vybavil jeho reklamáciu alebo ak sa domnieva, že predávajúci porušil jeho práva, má kupujúci (spotrebiteľ) právo obrátiť sa na predávajúceho so žiadosťou o nápravu mailom na adresu <span style={{ color: "#ff0000" }}><a style={{ color: "#ff0000" }} href="mailto:info@printexpert.sk">info@printexpert.sk</a></span>. Ak predávajúci na takúto žiadosť odpovie zamietavo alebo na ňu neodpovie do 30 dní odo dňa jej odoslania, má kupujúci (spotrebiteľ) právo podať návrh na začatie alternatívneho riešenia sporu subjektu alternatívneho riešenia sporov.<br />Subjektom alternatívneho riešenia sporov je orgán alternatívneho riešenia sporov uvedený v odseku 2 a oprávnená právnická osoba zapísaná v zozname podľa § 5 ods. 2. zákona č. 391/2014 Z. z. o alternatívnom riešení spotrebiteľských sporov a o zmene a doplnení niektorých zákonov. Subjektom alternatívneho riešenia sporov je aj Slovenská obchodná inšpekcia, Prievozská 32, P.O. Box 5, 820 07 Bratislava 27, resp. iná príslušná oprávnená právnická osoba zapísaná v zozname subjektov alternatívneho riešenia sporov vedenom Ministerstvom hospodárstva Slovenskej republiky (zoznam je dostupný na internetovej stránke <span style={{ color: "#ff0000" }}><a style={{ color: "#ff0000" }} href="http://www.mhsr.sk/" target="_blank" rel="noopener">www.mhsr.sk</a></span>).</p>
<p>Kupujúci (spotrebiteľ) je oprávnený si vybrať subjekt alternatívneho riešenia spotrebiteľských sporov na ktorý sa obráti. Spotrebiteľ môže na podanie návrhu na alternatívne riešenie svojho sporu využiť platformu pre riešenie sporov on-line, ktorá je dostupná na internetovej stránke <span style={{ color: "#ff0000" }}><a style={{ color: "#ff0000" }} href="http://ec.europa.eu/consumers/odr/" target="_blank" rel="noopener">http://ec.europa.eu/consumers/odr/</a></span>.</p>
<p>Podmienky alternatívneho riešenia sporu medzi spotrebiteľom a predávajúcim vyplývajúceho zo spotrebiteľskej zmluvy alebo súvisiaceho so spotrebiteľskou zmluvou bližšie upravuje zákon č. 391/2014<br />Z. z. o alternatívnom riešení spotrebiteľských sporov a o zmene a doplnení niektorých zákonov.</p>
<p><strong>9. Osobné údaje a ich ochrana</strong></p>
<p>9.1. Zmluvné strany sa dohodli, že kupujúci v prípade, že je fyzickou osobou je povinný oznámiť predávajúcemu v objednávke svoje meno a priezvisko, adresu trvalého bydliska vrátane PSČ, číslo telefónu a mailovú adresu.</p>
<p>9.2. Zmluvné strany sa dohodli, že kupujúci v prípade, že je právnickou osobou je povinný oznámiť predávajúcemu v objednávke svoje obchodné meno, adresu sídla vrátane PSČ, IČO, číslo telefónu a mailovú adresu.</p>
<p>9.3. Kupujúci si môže kedykoľvek skontrolovať a zmeniť poskytnuté osobné údaje, ako aj zrušiť svoju registráciu po prihlásení sa na internetovej stránke elektronického obchodu v časti &#8222;XY (napr. Môj profil)&#8220;.</p>
<p>9.4. Predávajúci týmto oznamuje kupujúcemu, že zmysle ust. § 10 ods. 3 písm. b. zákona č. 122/2013 Z.z. o ochrane osobných údajov a o zmene a doplnení niektorých zákonov v znení neskorších predpisov (ďalej len „ZnOOÚ“) predávajúci ako prevádzkovateľ bude v procese uzatvárania kúpnej zmluvy spracúvať osobné údaje kupujúceho bez jeho súhlasu ako dotknutej osoby, keďže spracúvanie osobných údajov kupujúceho bude vykonávané predávajúcim v predzmluvných vzťahoch s kupujúcim a spracúvanie osobných údajov kupujúceho je nevyhnutné na plnenie z kúpnej zmluvy, v ktorej vystupuje kupujúci ako jedna zo zmluvných strán.</p>
<p>9.5. Kupujúci môže zaškrtnutím príslušného políčka pred odoslaním objednávky vyjadriť svoj súhlas v zmysle ust. § 11 ods. 1 zákona, aby predávajúci spracoval a uschovával jeho osobné údaje, najmä tie, ktoré sú uvedené vyššie a/alebo ktoré sú potrebné pri činnosti predávajúceho týkajúcej sa zasielania informácií o nových produktoch, zľavách a akciách na ponúkaných tovaroch a spracovával ich vo všetkých svojich informačných systémoch, týkajúcich sa zasielania informácií o nových produktoch, zľavách a akciách na ponúkaných tovaroch.</p>
<p>9.6. Predávajúci sa zaväzuje, že bude s osobnými údajmi kupujúceho zaobchádzať a nakladať v súlade s platnými právnymi predpismi SR.</p>
<p>9.7. Predávajúci vyhlasuje, že v súlade s ust. § 6 ods. 2 písm. c. ZnOOÚ osobné údaje bude získavať výlučne na účel uvedený v týchto obchodných a reklamačných podmienkach.</p>
<p>9.8. Predávajúci vyhlasuje, že v súlade s ust. § 6 ods. 2 písm. e. ZnOOÚ bude získavať osobné údaje na iné účely, ako sú uvedené týchto obchodných a reklamačných podmienkach osobitne a zabezpečí, aby sa osobné údaje spracúvali a využívali výlučne spôsobom, ktorý zodpovedá účelu, na ktorý boli zhromaždené a že ich nebude združovať s osobnými údajmi, ktoré boli získané na iné účely.</p>
<p>9.9. Kupujúci udeľuje predávajúcemu súhlas podľa bodu 9.5 týchto reklamačných a obchodných podmienok na dobu určitú do splnenia účelu spracúvania osobných údajov kupujúceho. Predávajúci o splnení účelu spracúvania zabezpečí bezodkladne likvidáciu osobných údajov kupujúceho. Súhlas so spracovaním osobných údajov môže kupujúci odvolať kedykoľvek písomnou formou. Súhlas zanikne v lehote 1 mesiaca od doručenia odvolania súhlasu kupujúcim predávajúcemu.</p>
<p>9.10. Kupujúci bude pred odoslaním objednávky vyzvaný, aby zaškrtnutím políčka pred odoslaním objednávky potvrdil, že predávajúci mu dostatočným, zrozumiteľným a nezameniteľným spôsobom oznámil:</p>
<div>a. svoje identifikačné údaje, ktoré sú uvedené v čl. 1. týchto obchodných a reklamačných podmienok,</div>
<div>b. identifikačné údaje tretej strany, ktorou je spoločnosť, ktorá doručí kupujúcemu objednaný tovar tak, že tieto údaje sú uvedené v akceptácii,</div>
<div>c. účel spracúvania osobných údajov ktorým je uzavretie kúpnej zmluvy medzi predávajúcim a kupujúcim,</div>
<div>d. že bude spracúvať osobné údaje kupujúceho v rozsahu meno a priezvisko, adresu trvalého bydliska vrátane PSČ, číslo telefónu a mailovú adresu, ak je kupujúci fyzickou osobou a v rozsahu obchodné meno, adresu sídla vrátane PSČ, IČO, číslo telefónu a mailovú adresu ak je kupujúci právnickou osobou,</div>
<div>
<p>e. že požadované osobné údaje je kupujúci povinný poskytnúť,</p>
<p>9.11. Predávajúci vyhlasuje, že bude spracúvať osobné údaje v súlade s dobrými mravmi a bude konať spôsobom, ktorý neodporuje ZnOOÚ ani iným všeobecne záväzným právnym predpisom a ani ich nebude obchádzať. Predávajúci vyhlasuje, že súhlas dotknutej osoby si nebude vynucovať a ani podmieňovať hrozbou odmietnutia zmluvného vzťahu, služby, tovaru alebo povinnosti ustanovenej predávajúcemu.</p>
<p>9.12. Kupujúci má právo na základe písomnej žiadosti od predávajúceho vyžadovať</p>
</div>
<div>a. potvrdenie, či sú alebo nie sú osobné údaje o jeho osobe spracúvané,</div>
<div>b. účel spracúvania osobných údajov,</div>
<div>c. vo všeobecne zrozumiteľnej forme informácie o spracúvaní svojich osobných údajov v informačnom systéme a o jeho stave v rozsahu:</div>
<div>i. identifikačné údaje predávajúceho a zástupcu predávajúceho, ak bol vymenovaný,</div>
<div>ii. identifikačné údaje sprostredkovateľa; to neplatí, ak predávajúci pri získavaní osobných údajov nepostupuje podľa § 8 ZnOOÚ,</div>
<div>d. vo všeobecne zrozumiteľnej forme presné informácie o zdroji, z ktorého získal jeho osobné údaje na spracúvanie,</div>
<div>e. vo všeobecne zrozumiteľnej forme odpis jeho osobných údajov, ktoré sú predmetom spracúvania,</div>
<div>f. doplňujúce informácie, ktoré sú s ohľadom na všetky okolnosti a podmienky spracúvania osobných údajov potrebné pre kupujúceho na zaručenie jej práv a právom chránených záujmov v rozsahu najmä</div>
<div>i. poučenie o dobrovoľnosti alebo povinnosti poskytnúť požadované osobné údaje; ak predávajúci získava osobné údaje kupujúceho na základe súhlasu kupujúceho podľa § 11 ZnOOÚ, oznámi jej aj čas platnosti súhlasu, a ak kupujúceho povinnosť poskytnúť osobné údaje vyplýva z priamo vykonateľného právne záväzného aktu Európskej únie, medzinárodnej zmluvy, ktorou je Slovenská republika viazaná, alebo zákona, predávajúci oznámi kupujúcemu právny základ, ktorý jej túto povinnosť ukladá, a upovedomí ju o následkoch odmietnutia poskytnúť osobné údaje,</div>
<div>ii. informácie o tretích stranách, ak sa predpokladá alebo je zrejmé, že im budú osobné údaje poskytnuté,</div>
<div>iii. okruh príjemcov, ak sa predpokladá alebo je zrejmé, že im budú osobné údaje sprístupnené,</div>
<div>iv. formu zverejnenia, ak majú byť osobné údaje zverejnené,</div>
<div>v. tretie krajiny, ak sa predpokladá alebo je zrejmé, že sa do týchto krajín uskutoční prenos osobných údajov,</div>
<div>g. opravu jeho nesprávnych, neúplných alebo neaktuálnych osobných údajov, ktoré sú predmetom spracúvania,</div>
<div>h. likvidáciu jeho osobných údajov, ak bol splnený účel ich spracúvania; ak sú predmetom spracúvania úradné doklady obsahujúce osobné údaje, môže požiadať o ich vrátenie,</div>
<div>
<p>i. likvidáciu jeho osobných údajov, ktoré sú predmetom spracúvania, ak došlo k porušeniu ZnOOÚ alebo iného platného právneho predpisu SR.</p>
<p>9.13. Kupujúci na základe bezplatnej písomnej žiadosti má právo u predávajúceho namietať voči:</p>
</div>
<div>a. spracúvaniu jeho osobných údajov, o ktorých predpokladá, že sú alebo budú spracúvané na účely priameho marketingu bez jeho súhlasu a žiadať ich likvidáciu,</div>
<div>b. využívaniu osobných údajov uvedených v § 10 ods. 3 písm. d. na účely priameho marketingu v poštovom styku, alebo</div>
<div>
<p>c. poskytovaniu osobných údajov uvedených v § 10 ods. 3 písm. d. na účely priameho marketingu.</p>
<p>9.14. Kupujúci na základe bezplatnej písomnej žiadosti má právo u predávajúceho namietať voči spracúvaniu osobných údajov v prípadoch podľa § 10 ods. 3 písm. a), e), f) alebo g) ZnOOÚ vyslovením oprávnených dôvodov alebo predložením dôkazov o neoprávnenom zasahovaní do jej práv a právom chránených záujmov, ktoré sú alebo môžu byť v konkrétnom prípade takýmto spracúvaním osobných údajov poškodené; ak tomu nebránia zákonné dôvody a preukáže sa, že námietka kupujúceho je oprávnená, predávajúci je povinný osobné údaje, ktorých spracúvanie kupujúci namietal, bez zbytočného odkladu blokovať a zlikvidovať ihneď, ako to okolnosti dovolia.</p>
<p>9.15. Kupujúci na základe písomnej žiadosti alebo osobne, ak vec neznesie odklad, ďalej má právo u predávajúceho kedykoľvek namietať a nepodrobiť sa rozhodnutiu predávajúceho, ktoré by malo pre neho právne účinky alebo významný dosah, ak sa také rozhodnutie vydá výlučne na základe úkonov automatizovaného spracúvania jej osobných údajov. Kupujúci má právo žiadať predávajúceho o preskúmanie vydaného rozhodnutia metódou odlišnou od automatizovanej formy spracúvania, pričom predávajúci je povinný žiadosti kupujúceho vyhovieť, a to tak, že rozhodujúcu úlohu pri preskúmaní rozhodnutia bude mať oprávnená osoba; o spôsobe preskúmania a výsledku zistenia predávajúci informuje kupujúceho v lehote podľa ods. 9.18. týchto Obchodných podmienok. Kupujúci nemá toto právo iba v prípade, ak to ustanovuje osobitný zákon, v ktorom sú upravené opatrenia na zabezpečenie oprávnených záujmov kupujúceho, alebo ak v rámci predzmluvných vzťahov alebo počas existencie zmluvných vzťahov predávajúci vydal rozhodnutie, ktorým vyhovel požiadavke kupujúceho, alebo ak predávajúci na základe zmluvy prijal iné primerané opatrenia na zabezpečenie oprávnených záujmov kupujúceho.</p>
<p>9.16. Ak kupujúci uplatní svoje právo písomne a z obsahu jeho žiadosti vyplýva, že uplatňuje svoje právo, žiadosť sa považuje za podanú podľa tohto zákona; žiadosť podanú elektronickou poštou alebo faxom kupujúci doručí písomne najneskôr do troch dní odo dňa jej odoslania.</p>
<p>9.17. Kupujúci pri podozrení, že jeho osobné údaje sa neoprávnene spracúvajú, môže podať o tom oznámenie Úradu ma ochranu osobných údajov. Ak kupujúci nemá spôsobilosť na právne úkony v plnom rozsahu, jeho práva môže uplatniť zákonný zástupca.</p>
<p>9.18. Predávajúci je povinný písomne vybaviť žiadosť kupujúceho podľa tohto čl. týchto obchodných a reklamačných podmienok, resp. vyhovieť požiadavkám kupujúceho podľa ZnOOÚ a písomne ho informovať najneskoršie do 30 dní od prijatia žiadosti alebo požiadavky.</p>
<p>9.19. Obmedzenie práv kupujúceho podľa § 28 ods. 2 ZnOOÚ predávajúci bezodkladne písomne oznámi dotknutej osobe a Úradu ma ochranu osobných údajov.</p>
<p>9.20. Predávajúci oznamuje týmto kupujúcemu, že v súlade s ust. § 15 ods. 1 písm. e. bod 3 a bod 4 ZnOOÚ pri spracúvaní osobných údajov kupujúceho sa predpokladá, že osobné údaje kupujúceho budú poskytnuté a sprístupnené nasledovným tretím stranám, resp. okruhu príjemcov:</p>
<p><strong>Slovak Parcel Service s.r.o.</strong>, Senecká cesta 1 , 900 28, Bratislava, IČO: 31 329 217, zapísaná v Obchodnom registri Okresného súdu Bratislava, Oddiel Sa, Vložka číslo: 3215/B. Informačné systémy elektronického obchodu predávajúceho sú zaregistrované v zmysle zákona č. 122/2013 Z. z. o ochrane osobných údajov.</p>
<p><strong>10. Odstúpenie od kúpnej zmluvy</strong></p>
<p>10.1. Ak predávajúci nemôže splniť svoje povinnosti vyplývajúce mu z kúpnej zmluvy z dôvodu vypredania zásob, nedostupnosti tovaru, alebo ak výrobca, dovozca alebo dodávateľ tovaru dohodnutého v kúpnej zmluve prerušil výrobu alebo vykonal tak závažné zmeny, ktoré znemožnili realizáciu splnenia povinností predávajúceho vyplývajúcich z kúpnej zmluvy alebo z dôvodov vyššej moci alebo ak ani pri vynaložení všetkého úsilia, ktoré možno od neho spravodlivo požadovať nie je schopný dodať tovar zákazníkovi v lehote určenej týmito obchodnými podmienkami alebo v cene, ktorá je uvedená v objednávke, predávajúci je povinný o tejto skutočnosti okamžite informovať kupujúceho a zároveň je povinný ponúknuť kupujúcemu náhradné plnenie alebo možnosť pre kupujúceho odstúpiť od kúpnej zmluvy (stornovať objednávku). V prípade, ak kupujúci odstúpi od kúpnej zmluvy z dôvodov uvedených v tomto bode týchto reklamačných a obchodných podmienok, je predávajúci povinný vrátiť kupujúcemu už zaplatenú zálohu za tovar dohodnutý v kúpnej zmluve v lehote 14 dní od oznámenia o odstúpení od zmluvy prevodom na účet určený kupujúcim.</p>
<p>10.2. Kupujúci je oprávnený odstúpiť od kúpnej zmluvy bez udania dôvodu v súlade s ust. § 7 a nasl. Zákona č. 102/2014 Z.z. o ochrane spotrebiteľa pri predaji na diaľku (ďalej len „Zákon o ochrane spotrebiteľa pri predaji na diaľku“) v lehote 14 dní od prevzatia tovaru, resp. odo dňa uzavretia zmluvy o poskytnutí služby alebo zmluvy o poskytovaní elektronického obsahu nedodávaného na hmotnom nosiči, ak predávajúci včas a riadne splnil informačné povinnosti podľa ust. § 3 Zákona o ochrane spotrebiteľa pri predaji na diaľku.</p>
<p>10.3. Kupujúci má právo v rámci tejto lehoty po prevzatí tovar rozbaliť a odskúšať obdobným spôsobom ako je obvyklé pri nákupe v klasickom „kamennom“ obchode, a to v rozsahu potrebnom na zistenie povahy, vlastností a funkčnosti tovaru.</p>
<p>10.4. Lehota na odstúpenie od zmluvy začína plynúť v deň, keď kupujúci alebo ním určená tretia osoba s výnimkou dopravcu prevezme všetky časti objednaného tovaru, alebo ak sa</p>
</div>
<div>a. tovary objednané kupujúcim v jednej objednávke dodávajú oddelene, odo dňa prevzatia tovaru, ktorý bol dodaný ako posledný,</div>
<div>b. dodáva tovar pozostávajúci z viacerých dielov alebo kusov, odo dňa prevzatia posledného dielu alebo posledného kusu,</div>
<div>
<p>c. na základe zmluvy tovar dodáva opakovane počas vymedzeného obdobia, odo dňa prevzatia prvého dodaného tovaru.</p>
<p>10.5. Kupujúci môže odstúpiť od kúpnej zmluvy, predmetom ktorej je kúpa tovaru aj pred začatím plynutia lehoty na odstúpenie od zmluvy.</p>
<p>10.6. Odstúpenie od zmluvy musí kupujúci urobiť písomnou formou spôsobom nevzbudzujúcim pochybnosti, že došlo k odstúpeniu od zmluvy, alebo v podobe zápisu na inom trvanlivom nosiči alebo pomocou formulára, ktorý tvorí prílohu č. 1 týchto obchodných a reklamačných podmienok. Lehota na odstúpenie od zmluvy sa považuje za zachovanú, ak oznámenie o odstúpení od zmluvy bolo odoslané predávajúcemu najneskôr v posledný deň lehoty podľa ust. § 7 ods. 1 Zákona o ochrane spotrebiteľa pri predaji na diaľku.</p>
<p>10.7. Odstúpenie od kúpnej zmluvy podľa prechádzajúceho bodu týchto obchodných a reklamačných podmienok musí obsahovať informácie požadované vo formulári odstúpenia od kúpnej zmluvy, ktorý tvorí prílohu č. 1 týchto obchodných a reklamačných podmienok, najmä identifikáciu kupujúceho, číslo a dátum objednávky, presnú špecifikáciu tovaru, spôsob, akým má predávajúci vrátiť už prijaté plnenie, najmä číslo účtu a/alebo poštovú adresu kupujúceho.</p>
<p>10.8. Ak kupujúci odstúpi od kúpnej zmluvy, zrušuje sa od začiatku aj každá doplnková zmluva súvisiaca s kúpnou zmluvou, od ktorej kupujúci odstúpil. Od kupujúceho nie je možné požadovať žiadne náklady alebo iné platby v súvislosti so zrušením doplnkovej zmluvy okrem úhrady nákladov a platieb uvedených v ust. § 9 ods. 3, ust. § 10 ods. 3 a 5 Zákona o ochrane spotrebiteľa pri predaji na diaľku a ceny za službu, ak je predmetom zmluvy poskytnutie služby a došlo k úplnému poskytnutiu služby.</p>
<p>10.9. Kupujúci je povinný bez zbytočného odkladu, najneskôr však v lehote do 14 dní odo dňa odstúpenia od kúpnej zmluvy zaslať tovar späť na adresu sídla prevádzkovateľa alebo ho odovzdať predávajúcemu alebo osobe poverenej predávajúcim na prevzatie tovaru. To neplatí, ak predávajúci navrhol, že si tovar vyzdvihne osobne alebo prostredníctvom ním poverenej osoby. Lehota podľa prvej vety tohto bodu týchto obchodných a reklamačných podmienok sa považuje za zachovanú, ak bol tovar odovzdaný na prepravu najneskôr v posledný deň lehoty.</p>
<p>10.10. Kupujúci je povinný doručiť predávajúcemu tovar kompletný vrátane kompletnej dokumentácie, nepoškodený, podľa možnosti v originálnom obale a nepoužívaný.</p>
<p>10.11. Odporúča sa tovar poistiť. Zásielky na dobierku predávajúci nepreberá. Predávajúci je povinný bez zbytočného odkladu, najneskôr do 14 dní odo dňa doručenia oznámenia o odstúpení od zmluvy vrátiť kupujúcemu všetky platby, ktoré od neho prijal na základe kúpnej zmluvy alebo v súvislosti s ňou vrátane nákladov na dopravu, dodanie a poštovné a iných nákladov a poplatkov. Predávajúci nie je povinný vrátiť kupujúcemu platby podľa tohto bodu týchto obchodných a reklamačných podmienok pred tým, ako mu je doručený tovar alebo kým kupujúci nepreukáže zaslanie tovaru späť predávajúcemu, ibaže predávajúci navrhne, že si tovar vyzdvihne osobne alebo prostredníctvom ním poverenej osoby.</p>
<p>10.12. Kupujúci znáša náklady na vrátenie tovaru predávajúcemu alebo osobe poverenej predávajúcim na prevzatie tovaru. To neplatí, ak predávajúci súhlasil, že ich bude znášať sám alebo ak si nesplnil povinnosť podľa § 3 ods. 1 písm. i) Zákona o ochrane spotrebiteľa pri predaji na diaľku.</p>
<p>10.13. Kupujúci zodpovedá len za zníženie hodnoty tovaru, ktoré vzniklo v dôsledku takého zaobchádzania s tovarom, ktoré je nad rámec zaobchádzania potrebného na zistenie vlastností a funkčnosti tovaru. Spotrebiteľ nezodpovedá za zníženie hodnoty tovaru, ak si predávajúci nesplnil informačnú povinnosť o práve spotrebiteľa odstúpiť od zmluvy podľa § 3 ods. 1 písm. h) Zákona o ochrane spotrebiteľa pri predaji na diaľku.</p>
<p>10.14. Predávajúci je povinný vrátiť kupujúcemu kúpnu cenu za tovar rovnakým spôsobom, aký použil kupujúci pri svojej platbe, pokiaľ sa s kupujúcim nedohodne na inom spôsobe vrátenia platieb bez toho, aby kupujúcemu v tejto súvislosti boli účtované ďalšie poplatky.</p>
<p>10.15. V prípade, že kupujúci odstúpi od zmluvy a doručí predávajúcemu tovar, ktorý je používaný, poškodený alebo neúplný, zaväzuje sa kupujúci uhradiť predávajúcemu:</p>
</div>
<div>a. hodnotu, o ktorú sa znížila hodnota tovaru v zmysle ust. § 457 Občianskeho zákonníka v skutočnej výške</div>
<div>
<p>b. náklady, ktoré vznikli predávajúcemu v súvislosti s opravou tovaru a jeho uvedením do pôvodného stavu kalkulované podľa cenníka pre pozáručný servis tovaru. Kupujúci je povinný v zmysle tohto bodu reklamačných a obchodných podmienok predávajúcemu uhradiť predávajúcemu náhrady najviac vo výške rozdielu medzi kúpnou cenou tovaru a hodnotou tovaru v čase odstúpenia od kúpnej zmluvy.</p>
<p>10.16. V súlade s ust. § 7 ods. 6 Zákona o ochrane spotrebiteľa pri predaji na diaľku kupujúci nemôže odstúpiť od zmluvy, ktorej predmetom sú: − predaj tovaru zhotoveného podľa osobitných požiadaviek spotrebiteľa, tovaru vyrobeného na mieru alebo tovaru určeného osobitne pre jedného spotrebiteľa, − predaj tovaru uzavretého v ochrannom obale, ktorý nie je vhodné vrátiť z dôvodu ochrany zdravia alebo z hygienických dôvodov a ktorého ochranný obal bol po dodaní porušený, − predaj zvukových záznamov, obrazových záznamov, zvukovoobrazových záznamov, kníh alebo počítačového softvéru predávaných v ochrannom obale, ak spotrebiteľ tento obal rozbalil, − poskytovanie elektronického obsahu inak ako na hmotnom nosiči, ak sa jeho poskytovanie začalo s výslovným súhlasom spotrebiteľa a spotrebiteľ vyhlásil, že bol riadne poučený o tom, že vyjadrením tohto súhlasu stráca právo na odstúpenie od zmluvy. − predaj tovaru, ktorý bol v čase po uzavretí zmluvy a prevzatí tovaru od predávajúceho kupujúcemu zmontovaný, zložený alebo použitý takým spôsobom, že jeho opätovné uvedenie do pôvodného stavu predávajúcim nie je možné bez vynaloženia zvýšeného úsilia a zvýšených nákladov.</p>
<p>10.17. Ustanovenia čl. 10 týchto obchodných a reklamačných podmienok výslovne neplatia pre subjekty nespĺňajúce definíciu spotrebiteľa uvedenú v ust. § 2 písm. a) Zákona.</p>
<p><strong>11. Záverečné ustanovenia</strong></p>
<p>11.1. V prípade, ak je kúpna zmluva uzatvorená v písomnej forme, akákoľvek jej zmena musí mať písomnú formu.</p>
<p>11.2. Zmluvné strany sa dohodli, že komunikácia medzi nimi bude uskutočňovaná vo forme e-mailových správ.</p>
<p>11.3. Na vzťahy neupravené týmito obchodnými a reklamačnými podmienkami sa vzťahujú príslušné ustanovenia Občianskeho zákonníka, Zákona, zákona č. 22/2004 Z.z. o elektronickom obchode a o zmene a doplnení zákona č. 128/2002 Z.z. o štátnej kontrole vnútorného trhu vo veciach ochrany spotrebiteľa a o zmene a doplnení niektorých zákonov v znení zákona č. 284/2002 Z.z. v znení neskorších predpisov a Zákona č. 102/2014 Z.z. o ochrane spotrebiteľa pri predaji na diaľku.</p>
<p>11.4. Tieto obchodné a reklamačné podmienky nadobúdajú účinnosť voči kupujúcemu uzavretím kúpnej zmluvy.</p>
<p>11.5. Kupujúci bude pred odoslaním objednávky vyzvaný, aby zaškrtnutím políčka potvrdil, že sa s týmito obchodnými a reklamačnými podmienkami oboznámil, prečítal ich, porozumel ich obsahu a v celom rozsahu s nimi súhlasí.</p>
<p><strong>1. Právo na odstúpenie od kúpnej zmluvy </strong></p>
<p>Máte právo odstúpiť od tejto kúpnej zmluvy bez uvedenia dôvodu v lehote 14 dní. Lehota na odstúpenie od zmluvy uplynie 14 dní odo dňa keď Vy alebo Vami určená tretia osoba s výnimkou dopravcu prevezmete tovar. Pri uplatnení práva na odstúpenie od kúpnej zmluvy nás informujte o svojom rozhodnutí odstúpiť od tejto kúpnej zmluvy jednoznačným vyhlásením (napríklad listom zaslaným poštou, faxom) na adrese SHARK.SK j.s.a., Ivánska cesta 30/B, 821 04 Bratislava.</p>
<p>Lehota na odstúpenie od kúpnej zmluvy je zachovaná, ak zašlete oznámenie o uplatnení práva na odstúpenie od kúpnej zmluvy pred tým, ako uplynie lehota na odstúpenie od kúpnej zmluvy.</p>
<p><strong>2. Dôsledky odstúpenia od zmluvy </strong></p>
<p>V prípade odstúpenia od kúpnej zmluvy Vám vrátime všetky platby, ktoré ste uhradili v súvislosti s uzavretím kúpnej zmluvy, najmä kúpnu cenu vrátane nákladov na doručenie tovaru k Vám. To sa nevzťahuje na dodatočné náklady, ak ste si zvolili iný druh doručenia, ak ste si zvolili iný druh doručenia, ako je najlacnejší bežný spôsob doručenia, ktorý ponúkame ani na náklady za doplnkové služby, ak boli predmetom zmluvy a ak došlo k ich úplnému poskytnutiu. Platby Vám budú vrátené bez zbytočného odkladu a v každom prípade najneskôr do 14 dní odo dňa, keď nám bude doručené Vaše oznámenie o odstúpení od tejto kúpnej zmluvy. Ich úhrada bude uskutočnená rovnakým spôsobom, aký ste použili pri Vašej platbe, pokiaľ ste výslovne nesúhlasili s iným spôsobom platby, a to bez účtovania akýchkoľvek ďalších poplatkov. Platba za zakúpený tovar Vám bude uhradená až po doručení vráteného tovaru späť na našu adresu alebo po predložení dokladu preukazujúceho zaslanie tovaru späť, podľa toho, čo nastane skôr. Zašlite nám tovar späť alebo ho prineste na adresu sídla spoločnosti bez zbytočného odkladu a v každom prípade najneskôr do 14 dní odo dňa uplatnenia práva na odstúpenie od zmluvy. Lehota sa považuje za zachovanú, ak tovar odošlete späť pred uplynutím 14-dňovej lehoty. Priame náklady na vrátenie tovaru znášate Vy. Upozorňujeme Vás, že v prípade odstúpenia od kúpnej zmluvy zodpovedáte za akékoľvek zníženie hodnoty tovaru v dôsledku zaobchádzania s ním v čase od jeho doručenia do momentu jeho vrátenia iným spôsobom, než aký je potrebný na zistenie povahy, vlastností a funkčnosti tovaru.</p>

      </div>
    </div>
  </div>
  )
}
